#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "sym_differ_cli/help_controller"
require "sym_differ_cli/derivative_expressions_controller"

subcommand, *parameters_and_options = ARGV
options, parameters = parameters_and_options.partition { |o| o.start_with?("--") }.map(&:join)

result =
  case subcommand
  when "derive"
    controller = SymDifferCli::DerivativeExpressionsController.new

    case options
    when "--help"
      controller.display_help
    else
      controller.get_derivative_expression(parameters)
    end
  else
    SymDifferCli::HelpController.new.display_help
  end

puts result.message
